name = "Barely Functional"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b10a66770258e83a19c00ed4adbfa855bd3f3f527a6165b617e9b15050326985"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
