name = "Barely Functional"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e7a9eaad94ace29ae3874c672a202ab59f267d845c2d0915091e73e666e565"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
